ALTER TABLE services
ADD COLUMN price INTEGER DEFAULT 0 NOT NULL;

UPDATE services
SET price = CASE
    WHEN id = 'SOLARIUM' THEN 400
    WHEN id = 'POOL' THEN 200
    WHEN id = 'CRYOSAUNA' THEN 1000
    WHEN id = 'CROSSFIT' THEN 500
END
WHERE id IN ('SOLARIUM', 'POOL', 'CRYOSAUNA', 'CROSSFIT');